apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qt2ezxue7-nodejs-gitops
  description: This is GitOps manifest for qt2ezxue7-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=qt2ezxue7-nodejs
    backstage.io/kubernetes-id: qt2ezxue7-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: qt2ezxue7-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qt2ezxue7-nodejs
